---
var_all: '''production'' inventory, ''all'' group'
var_host: '''production'' inventory, ''all'' group'
var_1: '''production'' inventory, ''all'' group'
var_2: '''production'' inventory, ''all'' group'
var_3: '''production'' inventory, ''all'' group'
var_3_1: '''production'' inventory, ''all'' group'
var_3_2: '''production'' inventory, ''all'' group'
var_3_z: '''production'' inventory, ''all'' group'
var_4: '''production'' inventory, ''all'' group'
message_file: 'group_files/all/message.txt'
host_msg: '''producton'' inventory, ''all'' group'
